import {
  AlertTriangleIcon,
  ArrowDownIcon,
  ArrowUpIcon,
  BadgeCheckIcon,
  CheckCheck,
  ChevronsUpDownIcon,
  CloudDownloadIcon,
  EditIcon,
  EllipsisIcon,
  EyeIcon,
  EyeOffIcon,
  FileArchiveIcon,
  HomeIcon,
  LoaderIcon,
  LockIcon,
  type LucideIcon,
  Settings2Icon,
  SlashIcon,
  Trash2Icon,
  UsersIcon,
} from 'lucide-react'

export type IconType = LucideIcon

export const Icons = {
  update: EditIcon,
  verified: BadgeCheckIcon,
  fileArchive: FileArchiveIcon,
  cloudDownload: CloudDownloadIcon,
  eye: EyeIcon,
  eyeOff: EyeOffIcon,
  loader: LoaderIcon,
  alertTriangle: AlertTriangleIcon,
  slash: SlashIcon,
  arrowDown: ArrowDownIcon,
  arrowUp: ArrowUpIcon,
  chevronArrowUpDown: ChevronsUpDownIcon,
  settings: Settings2Icon,
  horizontalEllipsis: EllipsisIcon,
  delete: Trash2Icon,
  lock: LockIcon,
  doubleCheck: CheckCheck,
  users: UsersIcon,
  home: HomeIcon,
}
