export type Portfolio = {
  subCategory: string
  macro: string
  percent: number
  active: string
}

export type InvestorAllocation = {
  investorProfile: string
  investorType: string
  minRange: number
  maxRange?: number
  description: string
  portfolios: Portfolio[]
}

export const investorAllocations: InvestorAllocation[] = [
  {
    investorProfile: 'SC',
    investorType: 'IQ',
    minRange: 50000,
    maxRange: 150000,
    description: 'INVESTIDOR QUALIFICADO - CARTEIRA SUPER CONSERVADOR NC 50-150K',
    portfolios: [
      {subCategory: "Liquidez Diária", macro: "Pós-Fixado", percent: 10, active: "Trend Cash"},
        {subCategory: "CP", macro: "Pós-Fixado", percent: 10, active: "Capitânia Premium 45"},
        {subCategory: "CP", macro: "Pós-Fixado", percent: 10, active: "Sparta TOP FIC FI RF CP LP"},
        {subCategory: "DC", macro: "Pós-Fixado", percent: 20, active: "Brave I"},
        {subCategory: "EB", macro: "Pós-Fixado", percent: 15, active: "CDB 2028"},
        {subCategory: "EB", macro: "Prefixada", percent: 15, active: "CDB 2028"},
        {subCategory: "EB", macro: "Inflação", percent: 20, active: "CDB 2030"}
    ],
  },
  {
    investorProfile: 'SC',
    investorType: 'IQ',
    minRange: 150000,
    description: 'INVESTIDOR QUALIFICADO - CARTEIRA SUPER CONSERVADOR NC > 150K',
    portfolios: [
      {subCategory: "Liquidez Diária", macro: "Pós-Fixado", percent: 10, active: "Trend Cash"},
      {subCategory: "CP", macro: "Pós-Fixado", percent: 5, active: "Capitânia Premium 45"},
      {subCategory: "CP", macro: "Pós-Fixado", percent: 5, active: "Augme 45 II"},
      {subCategory: "CP", macro: "Pós-Fixado", percent: 5, active: "Sparta TOP FIC FI RF CP LP"},
      {subCategory: "CP", macro: "Pós-Fixado", percent: 5, active: "ARX Vinson"},
      {subCategory: "DC", macro: "Pós-Fixado", percent: 20, active: "Brave I"},
      {subCategory: "EB", macro: "Pós-Fixado", percent: 15, active: "CDB 2028"},
      {subCategory: "EB", macro: "Prefixada", percent: 15, active: "CDB 2028"},
      {subCategory: "EB", macro: "Inflação", percent: 20, active: "CDB 2030"}
    ],
  },

  {
    investorProfile: 'C',
    investorType: 'IQ',
    minRange: 50000,
    maxRange: 500000,
    description: 'INVESTIDOR QUALIFICADO - CARTEIRA CONSERVADOR NC 50-500K',
    portfolios: [
        {subCategory: "Liquidez Diária", macro: "Pós-Fixado", percent: 10, active: "Trend Cash"},
        {subCategory: "CP", macro: "Pós-Fixado", percent: 5, active: "Capitânia Premium 45"},
        {subCategory: "CP", macro: "Pós-Fixado", percent: 5, active: "Augme 45 II"},
        {subCategory: "CP", macro: "Pós-Fixado", percent: 5, active: "Sparta TOP FIC FI RF CP LP"},
        {subCategory: "CP", macro: "Pós-Fixado", percent: 5, active: "ARX Vinson"},
        {subCategory: "DC", macro: "Pós-Fixado", percent: 15, active: "Brave I"},
        {subCategory: "EB", macro: "Pós-Fixado", percent: 15, active: "CDB 2028"},
        {subCategory: "EB", macro: "Prefixada", percent: 10, active: "CDB 2028"},
        {subCategory: "EB", macro: "Inflação", percent: 15, active: "CDB 2030"},
        {subCategory: "TP", macro: "Inflação", percent: 10, active: "NTN-B (2026 a 2035)"},
        {subCategory: "LB", macro: "RV", percent: 5, active: "Dahlia Total Return"}
    ],
  },
  {
    investorProfile: 'C',
    investorType: 'IQ',
    minRange: 500000,
    maxRange: 1000000,
    description: 'INVESTIDOR QUALIFICADO - CARTEIRA CONSERVADOR NC 500K-1MM',
    portfolios: [
      {subCategory: "Liquidez Diária", macro: "Pós-Fixado", percent: 10.0, active: "Trend Cash"},
      {subCategory: "CP", macro: "Pós-Fixado", percent: 5.0, active: "Capitânia Premium 45"},
      {subCategory: "CP", macro: "Pós-Fixado", percent: 5.0, active: "Augme 45 II"},
      {subCategory: "CP", macro: "Pós-Fixado", percent: 5.0, active: "Sparta TOP FIC FI RF CP LP"},
      {subCategory: "CP", macro: "Pós-Fixado", percent: 5.0, active: "ARX Vinson"},
      {subCategory: "DC", macro: "Pós-Fixado", percent: 15.0, active: "Brave I"},
      {subCategory: "EB", macro: "Pós-Fixado", percent: 15.0, active: "CDB 2028"},
      {subCategory: "EB", macro: "Prefixada", percent: 10.0, active: "CDB 2028"},
      {subCategory: "EB", macro: "Inflação", percent: 10.0, active: "CDB 2030"},
      {subCategory: "TP", macro: "Inflação", percent: 15.0, active: "NTN-B (2026 a 2035)"},
      {subCategory: "LB", macro: "RV", percent: 2.5, active: "Dahlia Total Return"},
      {subCategory: "LB", macro: "RV", percent: 2.5, active: "Oceana LB"}
    ],
  },
  {
    investorProfile: 'C',
    investorType: 'IQ',
    minRange: 1000000,
    description: 'INVESTIDOR QUALIFICADO - CARTEIRA CONSERVADOR NC >1MM',
    portfolios: [
        {subCategory: "Liquidez Diária", macro: "Pós-Fixado", percent: 10.0, active: "Trend Cash"},
        {subCategory: "CP", macro: "Pós-Fixado", percent: 5.0, active: "Capitânia Premium 45"},
        {subCategory: "CP", macro: "Pós-Fixado", percent: 5.0, active: "Augme 45 II"},
        {subCategory: "CP", macro: "Pós-Fixado", percent: 5.0, active: "Sparta TOP FIC FI RF CP LP"},
        {subCategory: "CP", macro: "Pós-Fixado", percent: 5.0, active: "ARX Vinson"},
        {subCategory: "DC", macro: "Pós-Fixado", percent: 10.0, active: "Brave I"},
        {subCategory: "EB", macro: "Pós-Fixado", percent: 10.0, active: "CDB 2028"},
        {subCategory: "EB", macro: "Prefixada", percent: 7.5, active: "CDB 2028"},
        {subCategory: "TP", macro: "Prefixada", percent: 5.0, active: "NTN-F (2026 a 2030)"},
        {subCategory: "EB", macro: "Inflação", percent: 10.0, active: "CDB 2030"},
        {subCategory: "TP", macro: "Inflação", percent: 15.0, active: "NTN-B (2026 a 2035)"},
        {subCategory: "Macro", macro: "Multimercado", percent: 2.5, active: "Neo Provectus"},
        {subCategory: "Macro", macro: "Multimercado", percent: 5.0, active: "Kapitalo Zeta"},
        {subCategory: "LB", macro: "RV", percent: 2.5, active: "Dahlia Total Return"},
        {subCategory: "LB", macro: "RV", percent: 2.5, active: "Oceana LB"}
    ],
  },

  {
    investorProfile: 'M',
    investorType: 'IQ',
    minRange: 50000,
    maxRange: 500000,
    description: 'INVESTIDOR QUALIFICADO - CARTEIRA MODERADO NC 50-500K',
    portfolios: [
      {subCategory: "Liquidez Diária", macro: "Pós-Fixado", percent: 10, active: "Trend Cash"},
      {subCategory: "CP", macro: "Pós-Fixado", percent: 5, active: "Capitânia Premium 45"},
      {subCategory: "DC", macro: "Pós-Fixado", percent: 10, active: "Brave I"},
      {subCategory: "EB", macro: "Pós-Fixado", percent: 15, active: "CDB 2028"},
      {subCategory: "EB", macro: "Prefixada", percent: 15, active: "CDB 2028"},
      {subCategory: "EB", macro: "Inflação", percent: 10, active: "CDB 2030"},
      {subCategory: "TP", macro: "Inflação", percent: 15, active: "NTN-B (2030 a 2035)"},
      {subCategory: "Macro", macro: "Multimercado", percent: 5.0, active: "Gap Absoluto"},
      {subCategory: "LB", macro: "RV", percent: 5.0, active: "Oceana LB"},
      {subCategory: "LB", macro: "RV", percent: 5, active: "Dahlia Total Return"},
      {subCategory: "LO", macro: "RV", percent: 5, active: "Brasil Capital 30"}
    ],
  },
  {
    investorProfile: 'M',
    investorType: 'IQ',
    minRange: 500000,
    maxRange: 1000000,
    description: 'INVESTIDOR QUALIFICADO - CARTEIRA MODERADO NC 500K-1MM',
    portfolios: [
        {subCategory: "Liquidez Diária", macro: "Pós-Fixado", percent: 10, active: "Trend Cash"},
        {subCategory: "CP", macro: "Pós-Fixado", percent: 5, active: "Capitânia Premium 45"},
        {subCategory: "DC", macro: "Pós-Fixado", percent: 10, active: "Brave I"},
        {subCategory: "EB", macro: "Pós-Fixado", percent: 10, active: "CDB 2028"},
        {subCategory: "EB", macro: "Prefixada", percent: 10, active: "CDB 2028"},
        {subCategory: "EB", macro: "Inflação", percent: 10, active: "CDB 2030"},
        {subCategory: "TP", macro: "Inflação", percent: 15, active: "NTN-B (2030 a 2035)"},
        {subCategory: "Macro", macro: "Multimercado", percent: 5.0, active: "Gap Absoluto"},
        {subCategory: "Macro", macro: "Multimercado", percent: 5.0, active: "Neo Provectus"},
        {subCategory: "Quant", macro: "Multimercado", percent: 2.5, active: "Giant Zarathustra"},
        {subCategory: "Quant", macro: "Multimercado", percent: 2.5, active: "Giant Sigma"},
        {subCategory: "LB", macro: "RV", percent: 5.0, active: "Oceana LB"},
        {subCategory: "LB", macro: "RV", percent: 5, active: "Dahlia Total Return"},
        {subCategory: "LO", macro: "RV", percent: 5, active: "Brasil Capital 30"}
    ],
  },
  {
    investorProfile: 'M',
    investorType: 'IQ',
    minRange: 1000000,
    description: 'INVESTIDOR QUALIFICADO - CARTEIRA MODERADO NC >1MM',
    portfolios: [
      {subCategory: "Liquidez Diária", macro: "Pós-Fixado", percent: 10.0, active: "Trend Cash"},
      {subCategory: "CP", macro: "Pós-Fixado", percent: 5.0, active: "Capitânia Premium 45"},
      {subCategory: "DC", macro: "Pós-Fixado", percent: 10.0, active: "Brave I"},
      {subCategory: "EB", macro: "Pós-Fixado", percent: 10.0, active: "CDB 2028"},
      {subCategory: "EB", macro: "Prefixada", percent: 10.0, active: "CDB 2028"},
      {subCategory: "EB", macro: "Inflação", percent: 10.0, active: "CDB 2030"},
      {subCategory: "TP", macro: "Inflação", percent: 15.0, active: "NTN-B (2030 a 2035)"},
      {subCategory: "Macro", macro: "Multimercado", percent: 5.0, active: "Kapitalo Zeta"},
      {subCategory: "Macro", macro: "Multimercado", percent: 2.5, active: "Neo Provectus"},
      {subCategory: "Quant", macro: "Multimercado", percent: 2.5, active: "Kadima High Vol"},
      {subCategory: "Quant", macro: "Multimercado", percent: 2.5, active: "Giant Zarathustra"},
      {subCategory: "Quant", macro: "Multimercado", percent: 2.5, active: "Giant Sigma"},
      {subCategory: "LB", macro: "RV", percent: 3.3, active: "Oceana LB"},
      {subCategory: "LB", macro: "RV", percent: 3.3, active: "Dahlia Total Return"},
      {subCategory: "LB", macro: "RV", percent: 3.3, active: "Navi LB"},
      {subCategory: "LO", macro: "RV", percent: 2.5, active: "Brasil Capital 30"},
      {subCategory: "LO", macro: "RV", percent: 2.5, active: "Brasil Capital 30"}
    ],
  },

  {
    investorProfile: 'A',
    investorType: 'IQ',
    minRange: 50000,
    maxRange: 500000,
    description: 'INVESTIDOR QUALIFICADO - CARTEIRA AGRESSIVO NC 50-500K',
    portfolios: [
      {subCategory: "Liquidez Diária", macro: "Pós-Fixado", percent: 10, active: "Trend Cash"},
        {subCategory: "DC", macro: "Pós-Fixado", percent: 10, active: "Brave I"},
        {subCategory: "EB", macro: "Pós-Fixado", percent: 10, active: "CDB 2028"},
        {subCategory: "EB", macro: "Prefixada", percent: 15, active: "CDB 2028"},
        {subCategory: "EB", macro: "Inflação", percent: 10, active: "CDB 2030"},
        {subCategory: "TP", macro: "Inflação", percent: 15, active: "NTN-B (2030 a 2035)"},
        {subCategory: "Macro", macro: "Multimercado", percent: 5.0, active: "Gap Absoluto"},
        {subCategory: "LB", macro: "RV", percent: 5.0, active: "Oceana LB"},
        {subCategory: "LB", macro: "RV", percent: 5, active: "Dahlia Total Return"},
        {subCategory: "LO", macro: "RV", percent: 5, active: "Brasil Capital 30"},
        {subCategory: "LO", macro: "RV", percent: 5, active: "Constellation"},
        {subCategory: "LO", macro: "RV", percent: 5, active: "Forpus Ações"}
    ],
  },
  {
    investorProfile: 'A',
    investorType: 'IQ',
    minRange: 500000,
    maxRange: 1000000,
    description: 'INVESTIDOR QUALIFICADO - CARTEIRA AGRESSIVO NC 500K-1MM',
    portfolios: [
      {subCategory: "Liquidez Diária", macro: "Pós-Fixado", percent: 5, active: "Trend Cash"},
      {subCategory: "DC", macro: "Pós-Fixado", percent: 10, active: "Brave I"},
      {subCategory: "EB", macro: "Pós-Fixado", percent: 10, active: "CDB 2028"},
      {subCategory: "EB", macro: "Prefixada", percent: 10, active: "CDB 2028"},
      {subCategory: "EB", macro: "Inflação", percent: 10, active: "CDB 2030"},
      {subCategory: "TP", macro: "Inflação", percent: 15, active: "NTN-B (2030 a 2035)"},
      {subCategory: "Macro", macro: "Multimercado", percent: 5.0, active: "Gap Absoluto"},
      {subCategory: "Macro", macro: "Multimercado", percent: 5.0, active: "Neo Provectus"},
      {subCategory: "Quant", macro: "Multimercado", percent: 2.5, active: "Giant Zarathustra"},
      {subCategory: "Quant", macro: "Multimercado", percent: 2.5, active: "Giant Sigma"},
      {subCategory: "LB", macro: "RV", percent: 5.0, active: "Oceana LB"},
      {subCategory: "LB", macro: "RV", percent: 5, active: "Dahlia Total Return"},
      {subCategory: "LO", macro: "RV", percent: 5, active: "Brasil Capital 30"},
      {subCategory: "LO", macro: "RV", percent: 5, active: "Constellation"},
      {subCategory: "LO", macro: "RV", percent: 5, active: "Tork Long Only"}
    ],
  },
  {
    investorProfile: 'A',
    investorType: 'IQ',
    minRange: 1000000,
    description: 'INVESTIDOR QUALIFICADO - CARTEIRA AGRESSIVO NC >1MM',
    portfolios: [
        {subCategory: "Liquidez Diária", macro: "Pós-Fixado", percent: 5.0, active: "Trend Cash"},
        {subCategory: "DC", macro: "Pós-Fixado", percent: 10.0, active: "Brave I"},
        {subCategory: "EB", macro: "Pós-Fixado", percent: 10.0, active: "CDB 2028"},
        {subCategory: "EB", macro: "Prefixada", percent: 10.0, active: "CDB 2028"},
        {subCategory: "EB", macro: "Inflação", percent: 10.0, active: "CDB 2030"},
        {subCategory: "TP", macro: "Inflação", percent: 15.0, active: "NTN-B (2030 a 2035)"},
        {subCategory: "Macro", macro: "Multimercado", percent: 5.0, active: "Kapitalo Zeta"},
        {subCategory: "Macro", macro: "Multimercado", percent: 2.5, active: "Neo Provectus"},
        {subCategory: "Quant", macro: "Multimercado", percent: 2.5, active: "Kadima High Vol"},
        {subCategory: "Quant", macro: "Multimercado", percent: 2.5, active: "Giant Zarathustra"},
        {subCategory: "Quant", macro: "Multimercado", percent: 2.5, active: "Giant Sigma"},
        {subCategory: "LB", macro: "RV", percent: 3.5, active: "Oceana LB"},
        {subCategory: "LB", macro: "RV", percent: 4.0, active: "Dahlia Total Return"},
        {subCategory: "LB", macro: "RV", percent: 3.5, active: "Navi LB"},
        {subCategory: "LO", macro: "RV", percent: 3.5, active: "Brasil Capital 30"},
        {subCategory: "LO", macro: "RV", percent: 3.5, active: "Constellation"},
        {subCategory: "LO", macro: "RV", percent: 3.5, active: "Tork Long Only"},
        {subCategory: "LO", macro: "RV", percent: 3.5, active: "TB"}
    ],
  },

  {
    investorProfile: 'SA',
    investorType: 'IQ',
    minRange: 50000,
    maxRange: 500000,
    description: 'INVESTIDOR QUALIFICADO - CARTEIRA SUPER AGRESSIVO NC 50-500K',
    portfolios: [
        {subCategory: "Liquidez Diária", macro: "Pós-Fixado", percent: 5.0, active: "Trend Cash"},
        {subCategory: "DC", macro: "Pós-Fixado", percent: 5.0, active: "Brave I"},
        {subCategory: "EB", macro: "Pós-Fixado", percent: 5.0, active: "CDB 2028"},
        {subCategory: "EB", macro: "Prefixada", percent: 5.0, active: "CDB 2028"},
        {subCategory: "EB", macro: "Inflação", percent: 5.0, active: "CDB 2030"},
        {subCategory: "TP", macro: "Inflação", percent: 5.0, active: "NTN-B (2030 a 2035)"},
        {subCategory: "Macro", macro: "Multimercado", percent: 10.0, active: "Mar Absoluto II"},
        {subCategory: "Macro", macro: "Multimercado", percent: 5.0, active: "Gap Absoluto"},
        {subCategory: "LB", macro: "RV", percent: 10.0, active: "Oceana LB"},
        {subCategory: "LB", macro: "RV", percent: 5.0, active: "Dahlia Total Return"},
        {subCategory: "LB", macro: "RV", percent: 10.0, active: "Navi LB"},
        {subCategory: "LO", macro: "RV", percent: 10.0, active: "Brasil Capital 30"},
        {subCategory: "LO", macro: "RV", percent: 10.0, active: "Constellation"},
        {subCategory: "LO", macro: "RV", percent: 10.0, active: "Tork Long Only"}
    ],
  },
  {
    investorProfile: 'SA',
    investorType: 'IQ',
    minRange: 500000,
    maxRange: 1000000,
    description: 'INVESTIDOR QUALIFICADO - CARTEIRA SUPER AGRESSIVO NC 500K-1MM',
    portfolios: [
        {subCategory: "Liquidez Diária", macro: "Pós-Fixado", percent: 5.0, active: "Trend Cash"},
        {subCategory: "DC", macro: "Pós-Fixado", percent: 5.0, active: "Brave I"},
        {subCategory: "EB", macro: "Pós-Fixado", percent: 5.0, active: "CDB 2028"},
        {subCategory: "EB", macro: "Prefixada", percent: 5.0, active: "CDB 2028"},
        {subCategory: "EB", macro: "Inflação", percent: 5.0, active: "CDB 2030"},
        {subCategory: "TP", macro: "Inflação", percent: 5.0, active: "NTN-B (2030 a 2035)"},
        {subCategory: "Macro", macro: "Multimercado", percent: 5.0, active: "Gap Absoluto"},
        {subCategory: "Macro", macro: "Multimercado", percent: 5.0, active: "Neo Provectus"},
        {subCategory: "Macro", macro: "Multimercado", percent: 5.0, active: "Mar Absoluto II"},
        {subCategory: "LB", macro: "RV", percent: 5.0, active: "Oceana LB"},
        {subCategory: "LB", macro: "RV", percent: 5.0, active: "Dahlia Total Return"},
        {subCategory: "LB", macro: "RV", percent: 5.0, active: "Navi LB"},
        {subCategory: "LB", macro: "RV", percent: 5.0, active: "Sharp LB"},
        {subCategory: "LO", macro: "RV", percent: 10.0, active: "Brasil Capital 30"},
        {subCategory: "LO", macro: "RV", percent: 10.0, active: "Constellation"},
        {subCategory: "LO", macro: "RV", percent: 5.0, active: "Tork Long Only"},
        {subCategory: "LO", macro: "RV", percent: 5.0, active: "TB"},
        {subCategory: "LO", macro: "RV", percent: 5.0, active: "Forpus Ações"}
    ],
  },
  {
    investorProfile: 'SA',
    investorType: 'IQ',
    minRange: 1000000,
    description: 'INVESTIDOR QUALIFICADO - CARTEIRA SUPER AGRESSIVO NC >1MM',
    portfolios: [
      {subCategory: "Liquidez Diária", macro: "Pós-Fixado", percent: 5, active: "Trend Cash"},
      {subCategory: "DC", macro: "Pós-Fixado", percent: 5, active: "Brave I"},
      {subCategory: "EB", macro: "Pós-Fixado", percent: 5, active: "CDB 2028"},
      {subCategory: "EB", macro: "Prefixada", percent: 5, active: "CDB 2028"},
      {subCategory: "EB", macro: "Inflação", percent: 5, active: "CDB 2030"},
      {subCategory: "TP", macro: "Inflação", percent: 5, active: "NTN-B (2030 a 2035)"},
      {subCategory: "Macro", macro: "Multimercado", percent: 5, active: "Kapitalo Zeta"},
      {subCategory: "Macro", macro: "Multimercado", percent: 2.5, active: "Neo Provectus"},
      {subCategory: "Macro", macro: "Multimercado", percent: 2.5, active: "Mar Absoluto II"},
      {subCategory: "Macro", macro: "Multimercado", percent: 2.5, active: "Gap Absoluto"},
      {subCategory: "Quant", macro: "Multimercado", percent: 2.5, active: "Kadima High Vol"},
      {subCategory: "Quant", macro: "Multimercado", percent: 2.5, active: "Giant Zarathustra"},
      {subCategory: "Quant", macro: "Multimercado", percent: 2.5, active: "Giant Sigma"},
      {subCategory: "LB", macro: "RV", percent: 5, active: "Oceana LB"},
      {subCategory: "LB", macro: "RV", percent: 5, active: "Dahlia Total Return"},
      {subCategory: "LB", macro: "RV", percent: 5, active: "Navi LB"},
      {subCategory: "LB", macro: "RV", percent: 5, active: "Sharp LB"},
      {subCategory: "LO", macro: "RV", percent: 5, active: "Brasil Capital 30"},
      {subCategory: "LO", macro: "RV", percent: 5, active: "Constellation"},
      {subCategory: "LO", macro: "RV", percent: 5, active: "Tork Long Only"},
      {subCategory: "LO", macro: "RV", percent: 5, active: "TB"},
      {subCategory: "LO", macro: "RV", percent: 5, active: "Forpus Ações"},
      {subCategory: "LO", macro: "RV", percent: 5, active: "Bogari Value"}
    ],
  },

  
  {
    investorProfile: 'SC',
    investorType: 'IG',
    minRange: 50000,
    maxRange: 150000,
    description: 'INVESTIDOR GESTOR - CARTEIRA SUPER CONSERVADOR NC 50-150K',
    portfolios: [
        {subCategory: "Liquidez Diária", macro: "Pós-Fixado", percent: 10, active: "Trend Cash"},
        {subCategory: "CP", macro: "Pós-Fixado", percent: 10, active: "Capitânia Premium 45"},
        {subCategory: "CP", macro: "Pós-Fixado", percent: 10, active: "Sparta TOP FIC FI RF CP LP"},
        {subCategory: "CP", macro: "Pós-Fixado", percent: 10, active: "Augme 45 II"},
        {subCategory: "EB", macro: "Pós-Fixado", percent: 20, active: "CDB 2028"},
        {subCategory: "EB", macro: "Prefixada", percent: 20, active: "CDB 2028"},
        {subCategory: "EB", macro: "Inflação", percent: 20, active: "CDB 2030"}
    ],
  },
  {
    investorProfile: 'SC',
    investorType: 'IG',
    minRange: 150000,
    description: 'INVESTIDOR QUALIFICADO - CARTEIRA SUPER CONSERVADOR NC > 150K',
    portfolios: [
        {subCategory: "Liquidez Diária", macro: "Pós-Fixado", percent: 10, active: "Trend Cash"},
        {subCategory: "CP", macro: "Pós-Fixado", percent: 10, active: "Capitânia Premium 45"},
        {subCategory: "CP", macro: "Pós-Fixado", percent: 10, active: "Augme 45 II"},
        {subCategory: "CP", macro: "Pós-Fixado", percent: 10, active: "Sparta TOP FIC FI RF CP LP"},
        {subCategory: "CP", macro: "Pós-Fixado", percent: 10, active: "ARX Vinson"},
        {subCategory: "EB", macro: "Pós-Fixado", percent: 15, active: "CDB 2028"},
        {subCategory: "EB", macro: "Prefixada", percent: 15, active: "CDB 2028"},
        {subCategory: "EB", macro: "Inflação", percent: 20, active: "CDB 2030"}
    ],
  },
  {
    investorProfile: 'C',
    investorType: 'IG',
    minRange: 50000,
    maxRange: 500000,
    description: 'INVESTIDOR GESTOR - CARTEIRA CONSERVADOR NC 50-500K',
    portfolios: [
      {subCategory: "Liquidez Diária", macro: "Pós-Fixado", percent: 10.0, active: "Trend Cash"},
      {subCategory: "CP", macro: "Pós-Fixado", percent: 7.5, active: "Capitânia Premium 45"},
      {subCategory: "CP", macro: "Pós-Fixado", percent: 7.5, active: "Augme 45 II"},
      {subCategory: "CP", macro: "Pós-Fixado", percent: 7.5, active: "Sparta TOP FIC FI RF CP LP"},
      {subCategory: "CP", macro: "Pós-Fixado", percent: 7.5, active: "ARX Vinson"},
      {subCategory: "EB", macro: "Pós-Fixado", percent: 15.0, active: "CDB 2028"},
      {subCategory: "EB", macro: "Prefixada", percent: 15.0, active: "CDB 2028"},
      {subCategory: "EB", macro: "Inflação", percent: 15.0, active: "CDB 2030"},
      {subCategory: "TP", macro: "Inflação", percent: 10.0, active: "NTN-B (2026 a 2035)"},
      {subCategory: "LB", macro: "RV", percent: 5.0, active: "Dahlia Total Return"}
    ],
  },
  {
    investorProfile: 'C',
    investorType: 'IG',
    minRange: 500000,
    maxRange: 1000000,
    description: 'INVESTIDOR GESTOR - CARTEIRA CONSERVADOR NC 500-1MM',
    portfolios: [
      {subCategory: "Liquidez Diária", macro: "Pós-Fixado", percent: 10.0, active: "Trend Cash"},
      {subCategory: "CP", macro: "Pós-Fixado", percent: 7.5, active: "Capitânia Premium 45"},
      {subCategory: "CP", macro: "Pós-Fixado", percent: 7.5, active: "Augme 45 II"},
      {subCategory: "CP", macro: "Pós-Fixado", percent: 7.5, active: "Sparta TOP FIC FI RF CP LP"},
      {subCategory: "CP", macro: "Pós-Fixado", percent: 7.5, active: "ARX Vinson"},
      {subCategory: "EB", macro: "Pós-Fixado", percent: 15.0, active: "CDB 2028"},
      {subCategory: "EB", macro: "Prefixada", percent: 15.0, active: "CDB 2028"},
      {subCategory: "EB", macro: "Inflação", percent: 10.0, active: "CDB 2030"},
      {subCategory: "TP", macro: "Inflação", percent: 15.0, active: "NTN-B (2026 a 2035)"},
      {subCategory: "LB", macro: "RV", percent: 2.5, active: "Dahlia Total Return"},
      {subCategory: "LB", macro: "RV", percent: 2.5, active: "Oceana LB"}
    ],
  },
  {
    investorProfile: 'M',
    investorType: 'IG',
    minRange: 50000,
    maxRange: 500000,
    description: 'INVESTIDOR GESTOR - CARTEIRA MODERADO NC 50-500K',
    portfolios: [
        {subCategory: "Liquidez Diária", macro: "Pós-Fixado", percent: 10.0, active: "Trend Cash"},
        {subCategory: "CP", macro: "Pós-Fixado", percent: 5.0, active: "Capitânia Premium 45"},
        {subCategory: "CP", macro: "Pós-Fixado", percent: 5.0, active: "Augme 45 II"},
        {subCategory: "EB", macro: "Pós-Fixado", percent: 20.0, active: "CDB 2028"},
        {subCategory: "EB", macro: "Prefixada", percent: 15.0, active: "CDB 2028"},
        {subCategory: "EB", macro: "Inflação", percent: 10.0, active: "CDB 2030"},
        {subCategory: "TP", macro: "Inflação", percent: 15.0, active: "NTN-B (2030 a 2035)"},
        {subCategory: "Macro", macro: "Multimercado", percent: 5.0, active: "Gap Absoluto"},
        {subCategory: "LB", macro: "RV", percent: 5.0, active: "Oceana LB"},
        {subCategory: "LB", macro: "RV", percent: 5.0, active: "Dahlia Total Return"},
        {subCategory: "LO", macro: "RV", percent: 5.0, active: "Brasil Capital 30"}
    ],
  },
  {
    investorProfile: 'M',
    investorType: 'IG',
    minRange: 500000,
    maxRange: 1000000,
    description: 'INVESTIDOR GESTOR - CARTEIRA MODERADO NC 500-1MM',
    portfolios: [
        {subCategory: "Liquidez Diária", macro: "Pós-Fixado", percent: 10.0, active: "Trend Cash"},
        {subCategory: "CP", macro: "Pós-Fixado", percent: 5.0, active: "Capitânia Premium 45"},
        {subCategory: "CP", macro: "Pós-Fixado", percent: 5.0, active: "Augme 45 II"},
        {subCategory: "CP", macro: "Pós-Fixado", percent: 5.0, active: "Sparta TOP FIC FI RF CP LP"},
        {subCategory: "EB", macro: "Pós-Fixado", percent: 10.0, active: "CDB 2028"},
        {subCategory: "EB", macro: "Prefixada", percent: 10.0, active: "CDB 2028"},
        {subCategory: "EB", macro: "Inflação", percent: 10.0, active: "CDB 2030"},
        {subCategory: "TP", macro: "Inflação", percent: 15.0, active: "NTN-B (2030 a 2035)"},
        {subCategory: "Macro", macro: "Multimercado", percent: 5.0, active: "Gap Absoluto"},
        {subCategory: "Macro", macro: "Multimercado", percent: 5.0, active: "Mar Absoluto II"},
        {subCategory: "Quant", macro: "Multimercado", percent: 2.5, active: "Giant Zarathustra"},
        {subCategory: "Quant", macro: "Multimercado", percent: 2.5, active: "Giant Sigma"},
        {subCategory: "LB", macro: "RV", percent: 5.0, active: "Oceana LB"},
        {subCategory: "LB", macro: "RV", percent: 5.0, active: "Dahlia Total Return"},
        {subCategory: "LO", macro: "RV", percent: 5.0, active: "Brasil Capital 30"}
    ],
  },
  {
    investorProfile: 'A',
    investorType: 'IG',
    minRange: 50000,
    maxRange: 500000,
    description: 'INVESTIDOR GESTOR - CARTEIRA AGRESSIVO NC 50-500K',
    portfolios: [
      {subCategory: "Liquidez Diária", macro: "Pós-Fixado", percent: 10.0, active: "Trend Cash"},
      {subCategory: "EB", macro: "Pós-Fixado", percent: 15.0, active: "CDB 2028"},
      {subCategory: "EB", macro: "Prefixada", percent: 15.0, active: "CDB 2028"},
      {subCategory: "EB", macro: "Inflação", percent: 15.0, active: "CDB 2030"},
      {subCategory: "TP", macro: "Inflação", percent: 15.0, active: "NTN-B (2030 a 2035)"},
      {subCategory: "Macro", macro: "Multimercado", percent: 5.0, active: "Gap Absoluto"},
      {subCategory: "LB", macro: "RV", percent: 5.0, active: "Oceana LB"},
      {subCategory: "LB", macro: "RV", percent: 5.0, active: "Dahlia Total Return"},
      {subCategory: "LO", macro: "RV", percent: 5.0, active: "Brasil Capital 30"},
      {subCategory: "LO", macro: "RV", percent: 5.0, active: "Constellation"},
      {subCategory: "LO", macro: "RV", percent: 5.0, active: "Forpus Ações"}
    ],
  },
  {
    investorProfile: 'A',
    investorType: 'IG',
    minRange: 500000,
    maxRange: 1000000,
    description: 'INVESTIDOR GESTOR - CARTEIRA AGRESSIVO NC 500-1MM',
    portfolios: [
      {subCategory: "Liquidez Diária", macro: "Pós-Fixado", percent: 5.0, active: "Trend Cash"},
      {subCategory: "EB", macro: "Pós-Fixado", percent: 15.0, active: "CDB 2028"},
      {subCategory: "EB", macro: "Prefixada", percent: 7.5, active: "CDB 2028"},
      {subCategory: "TP", macro: "Prefixada", percent: 7.5, active: "NTN-F (2026 a 2030)"},
      {subCategory: "EB", macro: "Inflação", percent: 10.0, active: "CDB 2030"},
      {subCategory: "TP", macro: "Inflação", percent: 15.0, active: "NTN-B (2030 a 2035)"},
      {subCategory: "Macro", macro: "Multimercado", percent: 5.0, active: "Gap Absoluto"},
      {subCategory: "Macro", macro: "Multimercado", percent: 5.0, active: "Mar Absoluto II"},
      {subCategory: "Quant", macro: "Multimercado", percent: 2.5, active: "Giant Zarathustra"},
      {subCategory: "Quant", macro: "Multimercado", percent: 2.5, active: "Giant Sigma"},
      {subCategory: "LB", macro: "RV", percent: 5.0, active: "Oceana LB"},
      {subCategory: "LB", macro: "RV", percent: 5.0, active: "Dahlia Total Return"},
      {subCategory: "LO", macro: "RV", percent: 5.0, active: "Brasil Capital 30"},
      {subCategory: "LO", macro: "RV", percent: 5.0, active: "Constellation"},
      {subCategory: "LO", macro: "RV", percent: 5.0, active: "Tork Long Only"}
    ],
  },
  {
    investorProfile: 'SA',
    investorType: 'IG',
    minRange: 50000,
    maxRange: 500000,
    description: 'INVESTIDOR GESTOR - CARTEIRA SUPER AGRESSIVO NC 50-500K',
    portfolios: [
        {subCategory: "Liquidez Diária", macro: "Pós-Fixado", percent: 5.0, active: "Trend Cash"},
        {subCategory: "CP", macro: "Pós-Fixado", percent: 5.0, active: "Capitânia Premium 45"},
        {subCategory: "EB", macro: "Pós-Fixado", percent: 5.0, active: "CDB 2028"},
        {subCategory: "EB", macro: "Prefixada", percent: 5.0, active: "CDB 2028"},
        {subCategory: "EB", macro: "Inflação", percent: 5.0, active: "CDB 2030"},
        {subCategory: "TP", macro: "Inflação", percent: 5.0, active: "NTN-B (2030 a 2035)"},
        {subCategory: "Macro", macro: "Multimercado", percent: 10.0, active: "Mar Absoluto II"},
        {subCategory: "Macro", macro: "Multimercado", percent: 5.0, active: "Gap Absoluto"},
        {subCategory: "LB", macro: "RV", percent: 10.0, active: "Oceana LB"},
        {subCategory: "LB", macro: "RV", percent: 5.0, active: "Dahlia Total Return"},
        {subCategory: "LB", macro: "RV", percent: 10.0, active: "Navi LB"},
        {subCategory: "LO", macro: "RV", percent: 10.0, active: "Brasil Capital 30"},
        {subCategory: "LO", macro: "RV", percent: 10.0, active: "Constellation"},
        {subCategory: "LO", macro: "RV", percent: 10.0, active: "Tork Long Only"}
    ],
  },
  {
    investorProfile: 'SA',
    investorType: 'IG',
    minRange: 500000,
    maxRange: 1000000,
    description: 'INVESTIDOR GESTOR - CARTEIRA SUPER AGRESSIVO NC 500-1MM',
    portfolios: [
      {subCategory: "Liquidez Diária", macro: "Pós-Fixado", percent: 5.0, active: "Trend Cash"},
        {subCategory: "CP", macro: "Pós-Fixado", percent: 5.0, active: "Capitânia Premium 45"},
        {subCategory: "EB", macro: "Pós-Fixado", percent: 5.0, active: "CDB 2028"},
        {subCategory: "EB", macro: "Prefixada", percent: 5.0, active: "CDB 2028"},
        {subCategory: "EB", macro: "Inflação", percent: 5.0, active: "CDB 2030"},
        {subCategory: "TP", macro: "Inflação", percent: 5.0, active: "NTN-B (2030 a 2035)"},
        {subCategory: "Macro", macro: "Multimercado", percent: 5.0, active: "Gap Absoluto"},
        {subCategory: "Macro", macro: "Multimercado", percent: 5.0, active: "Mar Absoluto II"},
        {subCategory: "Quant", macro: "Multimercado", percent: 2.5, active: "Giant Zarathustra"},
        {subCategory: "Quant", macro: "Multimercado", percent: 2.5, active: "Giant Sigma"},
        {subCategory: "LB", macro: "RV", percent: 5.0, active: "Oceana LB"},
        {subCategory: "LB", macro: "RV", percent: 10.0, active: "Dahlia Total Return"},
        {subCategory: "LO", macro: "RV", percent: 10.0, active: "Brasil Capital 30"},
        {subCategory: "LO", macro: "RV", percent: 10.0, active: "Constellation"},
        {subCategory: "LO", macro: "RV", percent: 10.0, active: "Tork Long Only"},
        {subCategory: "LO", macro: "RV", percent: 10.0, active: "Forpus Ações"}
    ],
  },
]
