POST http://localhost:3333/users
content-type: application/json

{
    "name": "Berman",
    "email": "bermanschultz29@gmail.com",
    "password": "password"
}

################################

POST http://localhost:3333/auth/magic-link/login
content-type: application/json

{
    "email": "bermanschultz29@gmail.com"
}


################################

POST http://localhost:3333/suitabilities
content-type: application/json

{
  "userId": "2ff31a05-7066-4f95-b99f-2d5fbf003f65",
  "questions": [
    {
      "questionId": 1,
      "choosedAlternativesId": [4]
    }, 
    {
      "questionId": 2,
      "choosedAlternativesId": [3]
    }, 
    {
      "questionId": 3,
      "choosedAlternativesId": [5]
    }, 
    {
      "questionId": 4,
      "choosedAlternativesId": [4]
    }, 
    {
      "questionId": 5,
      "choosedAlternativesId": [2]
    }, 
    {
      "questionId": 6,
      "choosedAlternativesId": [2]
    }, 
    {
      "questionId": 7,
      "choosedAlternativesId": [4]
    }, 
    {
      "questionId": 8,
      "choosedAlternativesId": [3]
    }, 
    {
      "questionId": 9,
      "choosedAlternativesId": [3]
    }, 
    {
      "questionId": 10,
      "choosedAlternativesId": [4]
    }, 
    {
      "questionId": 11,
      "choosedAlternativesId": [6]
    }, 
    {
      "questionId": 12,
      "choosedAlternativesId": [1]
    }
  ]
}

################################

GET http://localhost:3333/users/2ff31a05-7066-4f95-b99f-2d5fbf003f65/suitabilities

###

GET http://localhost:3333/users

##############################

POST http://localhost:3333/auth/magic-link/verify
content-type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImJlcm1hbnNjaHVsdHoyOUBnbWFpbC5jb20iLCJpYXQiOjE3MTc3MjgyNzMsImV4cCI6MTcxNzczMDA3M30.6jv_CI_ZnS1eyBf34kTjdbbVDRNsqLF_RFOICnL7awc"
    }
